### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by whyrusleeping** [Bren2010/proquint#1]
Could you please add a license to this repo? 

Thanks in advance!

**Comment by jbenet** [comment]
i think the code is properly licensed: https://github.com/Bren2010/proquint/blob/master/proquint.go#L1-L21

@Bren2010 may want to add a `LICENSE` file in the root anyway though

**Comment by Bren2010** [comment]
Yeah, I think it's licensed properly, but I've also copied it into its own file.

Nice hearing from you guys. :)
